default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: secudevcase1

production:
  <<: *default
  database: secudevcase1
